from typing import Literal

LoadPatternType = Literal[
            'DEAD',
            'SUPERDEAD',
            'LIVE',
            'REDUCELIVE',
            'QUAKE',
            'WIND',
            'SNOW',
            'OTHER',
            'MOVE',
            'TEMPERATURE',
            'ROOFLIVE',
            'NOTIONAL',
            'PATTERNLIVE',
            'WAVE',
            'BRAKING',
            'CENTRIFUGAL',
            'FRICTION',
            'ICE',
            'WINDONLIVELOAD',
            'HORIZONTALEARTHPRESSURE',
            'VERTICALEARTHPRESSURE',
            'EARTHSURCHARGE',
            'DOWNDRAG',
            'VEHICLECOLLISION',
            'VESSELCOLLISION',
            'TEMPERATUREGRADIENT',
            'SETTLEMENT',
            'SHRINKAGE',
            'CREEP',
            'WATERLOADPRESSURE',
            'LIVELOADSURCHARGE',
            'LOCKEDINFORCES',
            'PEDESTRIANLL',
            'PRESTRESS',
            'HYPERSTATIC',
            'BOUYANCY',
            'STREAMFLOW',
            'IMPACT',
            'CONSTRUCTION',]


LoadCaseType = Literal[
    'LINEAR_STATIC',
    'NONLINEAR_STATIC',
    'MODAL',
    'RESPONSE_SPECTRUM',
    'LINEAR_HISTORY',
    'NONLINEAR_HISTORY',
    'LINEAR_DYNAMIC',
    'NONLINEAR_DYNAMIC',
    'MOVING_LOAD',
    'BUCKLING',
    'STEADY_STATE',
    'POWER_SPECTRAL_DENSITY',
    'LINEAR_STATIC_MULTISTEP',
    'HYPERSTATIC',
    ]